import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TelegramProvider from "@/app/conponents/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html suppressHydrationWarning className="dark" data-theme="dark">
      <head>
          <script src="https://telegram.org/js/telegram-web-app.js?62"></script>
      </head>
        <body className="min-h-full flex flex-col">
          <TelegramProvider>
            {children}
          </TelegramProvider>
        </body>
      </html>
  );
}
